### ISSUE TITLE
歪头的图片会出现异常的宽脸

### ISSUE THREAD

**Issue by 0002kgHg** [fssorc/ComfyUI_FaceShaper#10]
看来这个比例是用绝对坐标来计算的，当人物是歪头的时候打破平衡就会出现宽脸的情况了。大佬能把脸的中轴作为纵坐标定位吗？

**Comment by 0002kgHg** [comment]
![企业微信截图_17242284482024](https://github.com/user-attachments/assets/c4ee98be-b960-4827-926e-abb3176d2af7)

**Comment by fssorc** [comment]
try V2, please

**Comment by 0002kgHg** [comment]
> try V2, please

结合faceanalysis中的facealign节点我已经完成定位的功能，不过还是非常感谢您的更新
