### ISSUE TITLE
landmark文件位置问题

### ISSUE THREAD

**Issue by K-O-N-B** [fssorc/ComfyUI_FaceShaper#11]
landmark文件从hugface上下载好了，但是应该放在什么位置呢。。。。。

![image](https://github.com/user-attachments/assets/cda341b4-3f04-45e7-88ad-eddf1eeed537)

用的秋叶启动器，提示说已经安装了dlib

**Comment by fssorc** [comment]
try V2 please, don't need dlib anymore

试试V2吧，不需要dlib了
