### ISSUE TITLE
V2 face swap is not as effective as V1

### ISSUE THREAD

**Issue by flybirdxx** [fssorc/ComfyUI_FaceShaper#13]
![workflow](https://github.com/user-attachments/assets/843b81cc-1dfd-49c1-91d8-a322a45ed6e9)
I tried V2 according to the workflow, but the final result is not very good, I don't know if there is something wrong with my process or what, or can you provide me with a sample workflow for V2, I will be very grateful, thank you!

**Comment by 0002kgHg** [comment]
https://github.com/fssorc/ComfyUI_FaceShaper/blob/main/workflowV2.png
不是有给工作流示例吗
