### ISSUE TITLE
small face

### ISSUE THREAD

**Issue by 0002kgHg** [fssorc/ComfyUI_FaceShaper#16]
这次的更新非常有效，但是我发现这次似乎是以上下两点做的限制，这使得大头的问题得到解决但是小头的问题依然严重，在某些差异较大的图像中，细长的头使得头颈肩比例问题很突出：
![17267118675058](https://github.com/user-attachments/assets/839d2f91-d3aa-4104-90ed-5995c80af610)

这是我修改的上版本的代码的结果：
![1726711609248](https://github.com/user-attachments/assets/90b51912-ffe1-43be-aba1-efe540f70560)

我使用的是左右两点做固定，再进行的变形，当然，和你的方法一样，固定上下两点会出现脸异常的窄或者脸异常的宽的问题，使用左右两点同样也有可能出现脸长或脸短的问题，但就我现在的测试来看固定左右两点似乎更稳定些。或许还有更好的解决方案？先水平方向上固定再垂直固定？

**Comment by fssorc** [comment]
![回复gitHub](https://github.com/user-attachments/assets/833b4a43-5280-4881-8b77-27f8e96b2feb)
用这次更新的JawLine模式，就是你想的那个算法。
