### ISSUE TITLE
Do dlib dependencies have requirements for the version of setuptools?

### ISSUE THREAD

**Issue by 807502278** [fssorc/ComfyUI_FaceShaper#4]
I switched many versions of dlib and setuptools, but I still got this error message.  
![image](https://github.com/user-attachments/assets/46624481-f635-4c0c-931a-c93d98aeaee8)

**Comment by 807502278** [comment]
Solved: Install setuptools <= 71.1.0 (If there is still an error, a system restart might be needed). It is recommended to write this in requirements.txt.

**Comment by WX-NPS1598** [comment]
> I switched many versions of dlib and setuptools, but I still got this error message.我切换了许多版本的 dlib 和 setuptools，但我仍然收到此错误消息。 ![image](https://private-user-images.githubusercontent.com/46019416/352973817-46624481-f635-4c0c-931a-c93d98aeaee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjAyNDIsIm5iZiI6MTcyMjMxOTk0MiwicGF0aCI6Ii80NjAxOTQxNi8zNTI5NzM4MTctNDY2MjQ0ODEtZjYzNS00YzBjLTkzMWEtYzkzZDk4YWVhZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA2MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZjU3NDU4M2RkZGY3OWMyNDcyZGVkYjAyNDNjYzFhNTdmMTU1OTNkMTRiMTQ3OWZlYmJmMTMyY2M2NzNmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yArdDnkojWb02Lrnlj_V0Fvj4GiOdYmj2O3UoH8DgjM)

我也是一样的问题，按照你说的操作后，依然解决不了

**Comment by WX-NPS1598** [comment]
> Solved: Install setuptools <= 71.1.0 (If there is still an error, a system restart might be needed). It is recommended to write this in requirements.txt.已解决：安装 setuptools <= 71.1.0（如果仍有错误，可能需要重新启动系统）。建议用requirements.txt写这个。

I have the same problem. I still can't solve it after following the instructions you said.

**Comment by TiptopFunk** [comment]
The latest dlib==19.24.4 will fail to build, try pip install dlib==19.24.2, [check here for reference](https://github.com/davisking/dlib/issues/2943)

**Comment by 807502278** [comment]
试试dlib==19.24.2

**Comment by fssorc** [comment]
when i start to write this code, i already install [ComfyUI_FaceAnalysis](https://github.com/cubiq/ComfyUI_FaceAnalysis)
so dlib has been done on my machine.

it is dblib==19.24.2 on linux

**Comment by 807502278** [comment]
A few days ago, the author of dlib said that they had removed the code that used setup tools. command. test
